[package]
name = "trybuild_bug"
version = "0.1.0"
authors = ["Manuel Morales <manuelmorales@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
trybuild = "1.0.24"
